#!/usr/bin/env bash
# print 'Best School' 10 times with a while loop
# Say 'Hi' on last loop, then Best School afterwards
num=0

while ((num<10));
do
    if ((num==9));
    then
        echo "Hi"
    else 
        echo "Best School"
    fi
    ((num++))
done
echo "Best School"
