#!/usr/bin/env bash
# displays bad luck for the 4th loop iteration
# displays good luck for the 8th loop iteration
# displays Best School for the other iterations
num=0

while ((num<10));
do
    if ((num==4));
    then
        echo "bad luck"
    elif ((num==8));
    then
        echo "good luck"
    else 
        echo "Best School"
    fi
    ((num++))
done
echo "Best School"
