#!/usr/bin/env bash
# displays numbers from 1 to 20 and:
# displays 4 and then bad luck from China for the 4th loop iteration
# displays 9 and then bad luck from Japan for the 9th loop iteration
# displays 17 and then bad luck from Italy for the 17th loop iteration
num=1

while ((num<21));
do
    if ((num==4));
    then
        echo $num
        echo "then bad luck from China"
    elif ((num==9));
    then
        echo $num
        echo "bad luck from Japan"
    elif ((num==17));
    then
        echo $num
        echo "bad luck from Italy"
    else 
        echo $num
    fi
    ((num++))
done
