#!/usr/bin/env bash
#displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59
min=1
hour=0

while ((hour<13));
do
    echo "Hour: $hour"

    while ((min<60));
    do
        echo $min
        ((min++))
    done
    min=1
    ((hour++))
done
    