#!/usr/bin/env bash
# displaysThe content of the current directory
# In a list formatWhere only the part of the 
# name after the first dash is displayed

files=$(ls)

for file in $files; do
    echo "$file" | cut -d '-' -f2
done
